// Generated by CoffeeScript 1.7.1
(function() {
  var njs_path, options;

  njs_path = require('path');

  module.exports = options = {
    'parser': {
      'delimiter': ',',
      'skip_empty_lines': true
    },
    'stream-transform': {
      'parallel': 1
    },
    'data': {
      'types': require('./lib/gtfs-types'),
      'info': require('timetable-data'),
      'home': (require('path')).dirname(require.resolve('timetable-data'))
    }
  };

}).call(this);
