// Generated by CoffeeScript 1.7.1
(function() {
  var TRM, alert, badge, datasources_home, debug, echo, get_datasource_infos, glob, help, info, log, njs_fs, njs_path, options, rainbow, rpr, urge, warn, whisper,
    __indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

  njs_path = require('path');

  njs_fs = require('fs');

  TRM = require('coffeenode-trm');

  rpr = TRM.rpr.bind(TRM);

  badge = 'timetable/datasource-infos';

  log = TRM.get_logger('plain', badge);

  info = TRM.get_logger('info', badge);

  whisper = TRM.get_logger('whisper', badge);

  alert = TRM.get_logger('alert', badge);

  debug = TRM.get_logger('debug', badge);

  warn = TRM.get_logger('warn', badge);

  help = TRM.get_logger('help', badge);

  urge = TRM.get_logger('urge', badge);

  echo = TRM.echo.bind(TRM);

  rainbow = TRM.rainbow.bind(TRM);

  options = require('../options');

  datasources_home = options['data']['home'];

  glob = require('glob');

  get_datasource_infos = function(home) {
    var R, collection, collection_name, filename, matcher, route, _i, _len, _ref;
    if (home == null) {
      home = datasources_home;
    }
    R = {};
    matcher = njs_path.join(home, '**/*.txt');
    matcher = njs_path.join(home, '**/*.txt-[a-z]{4}');
    info("collecting data sources from");
    info(rpr(matcher));
    _ref = glob.sync(matcher);
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      route = _ref[_i];
      filename = njs_path.basename(route, njs_path.extname(route));
      if (__indexOf.call(options['data']['types'], filename) < 0) {
        continue;
      }
      collection_name = njs_path.basename(njs_path.dirname(route));
      collection = R[collection_name] != null ? R[collection_name] : R[collection_name] = {};
      whisper(route);
      collection[filename] = route;
    }
    return R;
  };

  module.exports = get_datasource_infos();

}).call(this);
