// Generated by CoffeeScript 1.7.1

/* List of filenames that may contain GTFS data. */

(function() {
  module.exports = "agency calendar_dates calendar routes stop_times stops transfers trips".split(/\s+/);

}).call(this);
