// Generated by CoffeeScript 1.7.1
(function() {
  var TEXT, TRM, alert, badge, debug, echo, help, info, log, njs_fs, options, rainbow, rpr, transform_stream, urge, warn, whisper;

  njs_fs = require('fs');

  TEXT = require('coffeenode-text');

  TRM = require('coffeenode-trm');

  rpr = TRM.rpr.bind(TRM);

  badge = 'timetable/TRANSFORMERS';

  log = TRM.get_logger('plain', badge);

  info = TRM.get_logger('info', badge);

  whisper = TRM.get_logger('whisper', badge);

  alert = TRM.get_logger('alert', badge);

  debug = TRM.get_logger('debug', badge);

  warn = TRM.get_logger('warn', badge);

  help = TRM.get_logger('help', badge);

  urge = TRM.get_logger('urge', badge);

  echo = TRM.echo.bind(TRM);

  rainbow = TRM.rainbow.bind(TRM);

  transform_stream = require('stream-transform');

  options = require('../options');

  this.as_transformer = function(method) {
    return transform_stream(method, options['transformer']);
  };

  this.$as_pods = function() {
    var field_names, record_idx;
    record_idx = -1;
    field_names = null;
    return this.as_transformer((function(_this) {
      return function(record) {
        var R, field_idx, field_name, field_value, _i, _len;
        if ((record_idx += 1) === 0) {
          field_names = record;
          return;
        }
        R = {};
        for (field_idx = _i = 0, _len = record.length; _i < _len; field_idx = ++_i) {
          field_value = record[field_idx];
          field_name = field_names[field_idx];
          R[field_name] = field_value;
        }
        return R;
      };
    })(this));
  };

  this.$delete_prefix = function(prefix) {
    return this.as_transformer((function(_this) {
      return function(record) {
        var field_value, new_field_name, old_field_name;
        for (old_field_name in record) {
          field_value = record[old_field_name];
          if (!TEXT.starts_with(old_field_name, prefix)) {
            continue;
          }
          new_field_name = old_field_name.replace(prefix, '');
          if (new_field_name.length === 0) {
            continue;
          }

          /* TAINT should throw error */
          if (record[new_field_name] != null) {
            continue;
          }
          record[new_field_name] = field_value;
          delete record[old_field_name];
        }
        return record;
      };
    })(this));
  };

  this.$add_n4j_system_properties = function(isa, label) {
    return this.as_transformer((function(_this) {
      return function(record) {
        record['~isa'] = isa;
        record['~label'] = label;
        return record;
      };
    })(this));
  };

  this.$dasherize_field_names = function() {
    return this.as_transformer((function(_this) {
      return function(record) {
        var new_field_name, old_field_name;
        for (old_field_name in record) {
          new_field_name = old_field_name.replace(/_/g, '-');
          if (new_field_name === old_field_name) {
            continue;
          }
          _this._rename(record, old_field_name, new_field_name);
        }
        return record;
      };
    })(this));
  };

  this._rename = function(record, old_field_name, new_field_name) {
    this._copy(record, old_field_name, new_field_name, 'rename');
    delete record[old_field_name];
    return record;
  };

  this._copy = function(record, old_field_name, new_field_name, action) {
    var error;
    if (record[old_field_name] === void 0) {
      error = new Error("when trying to " + action + " field " + (rpr(old_field_name)) + " to " + (rpr(new_field_name)) + "\nfound that there is no field " + (rpr(old_field_name)) + " in\n" + (rpr(record)));
      error['code'] = 'no such field';
      throw error;
    }
    if (record[new_field_name] !== void 0) {
      throw new Error("when trying to " + action + " field " + (rpr(old_field_name)) + " to " + (rpr(new_field_name)) + "\nfound that field " + (rpr(new_field_name)) + " already present in\n" + (rpr(record)));
      error['code'] = 'duplicate field';
      throw error;
    }
    record[new_field_name] = record[old_field_name];
    return record;
  };

  this.$rename = function(old_field_name, new_field_name) {
    return this.as_transformer((function(_this) {
      return function(record) {
        return _this._rename(record, old_field_name, new_field_name);
      };
    })(this));
  };

  this.$copy = function(old_field_name, new_field_name) {
    return this.as_transformer((function(_this) {
      return function(record) {
        return _this._copy(record, old_field_name, new_field_name, 'copy');
      };
    })(this));
  };


  /* TAINT gtfs-specific method shouldnt appear here */


  /* TAINT consider sub-registries by node label */

  this.$register = function(registry) {
    return this.as_transformer((function(_this) {
      return function(record) {
        var gtfs_id, id, new_registry, old_registry;
        old_registry = registry['old'] != null ? registry['old'] : registry['old'] = {};
        new_registry = registry['new'] != null ? registry['new'] : registry['new'] = {};
        gtfs_id = record['%gtfs-id'];
        id = record['id'];
        if (gtfs_id != null) {
          if (old_registry[gtfs_id] != null) {
            throw new Error("already registered in `registry[ 'old' ]`: " + (rpr(record)));
          }
          old_registry[gtfs_id] = record;
        }
        if (id != null) {
          if (new_registry[id] != null) {
            throw new Error("already registered in `registry[ 'new' ]`: " + (rpr(record)));
          }
          new_registry[id] = record;
        }
        return record;
      };
    })(this));
  };

  this.show_and_quit = this.as_transformer(function(record) {
    if (typeof error !== "undefined" && error !== null) {
      throw error;
    }
    info(rpr(record));
    warn('aborting from `TRANSFORMERS.show_and_quit`');
    return process.exit();
  });

}).call(this);
